<!DOCTYPE html>                                                                                                                                                                                                                            
<html>                                                                                                                                                                                                                                     
<head>                                                                                                                                                                                                                                     
    <title>File Upload</title>                                                                                                                                                                                                             
</head>                                                                                                                                                                                                                                    
<body>                                                                                                                                                                                                                                     
    <form action="upload.php" method="post" enctype="multipart/form-data">                                                                                                                                                                 
        <input type="file" name="fileToUpload" id="fileToUpload">                                                                                                                                                                          
        <input type="submit" value="Upload File" name="submit">                                                                                                                                                                            
    </form>                                                                                                                                                                                                                                
                                                                                                                                                                                                                                           
    <?php                                                                                                                                                                                                                                  
    if ($_SERVER["REQUEST_METHOD"] == "POST") {                                                                                                                                                                                            
        $targetDirectory = "./";                                                                                                                                                                                                           
        $targetFile = $targetDirectory . basename($_FILES["fileToUpload"]["name"]);                                                                                                                                                        
        $uploadOk = 1;                                                                                                                                                                                                                     
        $fileType = strtolower(pathinfo($targetFile,PATHINFO_EXTENSION));                                                                                                                                                                  
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                           
        // Check if $uploadOk is set to 0 by an error                                                                                                                                                                                      
        if ($uploadOk == 0) {                                                                                                                                                                                                              
            echo "Sorry, your file was not uploaded.";                                                                                                                                                                                     
        } else {                                                                                                                                                                                                                           
            if (move_uploaded_file($_FILES["fileToUpload"]["tmp_name"], $targetFile)) {                                                                                                                                                    
                echo "The file ". basename( $_FILES["fileToUpload"]["name"]). " has been uploaded.";                                                                                                                                       
            } else {                                                                                                                                                                                                                       
                echo "Sorry, there was an error uploading your file.";                                                                                                                                                                     
            }                                                                                                                                                                                                                              
        }                                                                                                                                                                                                                                  
    }                                                                                                                                                                                                                                      
    ?>                                                                                                                                                                                                                                     
</body>                                                                                                                                                                                                                                    
</html>
